package: iceberg
output: client.gen.go

compatibility:
  circular-reference-limit: 20

generate:
  client: true
  models: true

output-options:
  response-type-suffix: ServerResponse
  user-templates:
    client-with-responses.tmpl: templates/client-with-responses.tmpl
